#!/bin/sh
clear
tput setaf 42
echo " this will be a github repo autoinstaller "
sleep 3
clear
tput setaf 2
echo " 1)clone all now"
echo " "
tput setaf 121
echo "     2)fine pick && choose"
read q
if [ $q = 1 ]
then
  clear
  cd $HOME
  git clone https://github.com/D8m0n/zsh
  cd zsh
  bash syntax
  bash zsh
  cd
  git clone https://github.com/D8m0n/termuxin
  git clone https://github.com/nickbriggs501/master
  git clone https://github.com/Ranginang67/DarkFly-Tool
  cd DarkFly-Tool
  chmod +x install.py
  python2 install.py
  sleep 4
  clear
  tput setaf 73
  echo " IF THAT DIDNT WORK WAIT FEW SECS I WILL ATTEMPT PYTHON3"
  sleep 4
  python3 install.py
  cd
  git clone https://github.com/Lin8x/Tool-X.git/
  cd Tool-X
  chmod +x install.aex
  ./install.aex
  cd
fi
if [ $q = 2 ]
then
  clear
  cd termuxin
  cat peekin.txt
fi
