#!/bin/sh
clear
echo " please choose system "
echo " "
echo " t):.Termux"
echo " "
echo "     l):.Debian-Linux"
echo " "
echo "         c):.Ios "
read a in
if [ $a = t ]
then
  clear
  pkg update && pkg upgrade
  pkg install nano git wget curl python python2
  pkg install science-repo x11-repo ncurses-utils 
  sleep 3
  clear
  tput setaf 6;echo " one moment pip kicked in and wants to do its dance"
  sleep 4
  clear
  pip install --upgrade pip
  pip install wheel main mechanize sparrow sphinx LICENSE lolcat php 
  cd
  git clone https://github.com/D8m0n/zsh
  cd /data/data/com.termux/files/home/zsh
  bash syntax
  sleep 2
  clear
  bash zsh
  cd
fi
if [ $a = l ]
then
  clear
  sudo apt update && sudo apt -y upgrade
  sudo apt install nano git wget curl python3 python
  pip install --upgrade pip
  clear
  pip install wheel main mechanize sphinx sparrow LICENSE lolcat
  cd
  git clone https://github.com/D8m0n/zsh
  cd /home/Damon/zsh
  bash syntax
  bash zsh
fi
if [ $a = c ]
then
  clear
  su
  apt update
  apt upgrade
  apt install wget curl nano sudo ncurses git python python3
  clear
  git clone https://github.com/D8m0n/zsh
  cd /var/root/zsh
  bash syntax
  bash zsh
  clear
  echo " add to sudoers?"
  echo "      Y/N"
  read b in
  if [ $b = n ]
  then 
    clear
    exit
  fi
  if [ $b = y ]
  then
    clear
    nano /etc/sudoers
    sleep 2
  fi
fi
cd
clear
echo " continue to github repos"
echo " Y/N"
read f in
if [ $f = y ]
then
  clear
  bash /data/data/com.termux/files/home/termuxin/bash2nd
  sleep 4
  bash /home/Damon/termuxin/bash2nd
  sleep 4
  bash /var/mobile/termuxin/bash2nd
fi


