#!/bin/sh
clear
echo "     READY ?"
echo " "
echo "           Y/N  "
if [ $f = n ]
then
  clear
  exit
fi
if [ $f = y ]
then
  cd
  clear
  apt update && apt upgrade
  apt install wget curl ncurses-utils git 
  sleep 2
  clear
  git clone https://github.com/D8m0n/zsh
  cd zsh
  bash syntax
  bash zsh
fi
sleep 3
cd
nano /data/data/com.termux/files/home/.zshrc
